service:
  port: 9005
  name: broker-1
session:
  secret: game
database:
  user:
    connection: mongodb://localhost:27017/users
    collection: users
  account:
    connection: mongodb://localhost:27017/accounts
    collection: accounts
  servers:
    connection: mongodb://localhost:27017/servers
    collection: servers
  items: 
    connection: mongodb://localhost:27017/items
    collection: items
  guild:
    connection: mongodb://localhost:27017/guilds
    collection: guilds
game:
  version: 29
  messages:
    - "    Welcome to DragonBound 3.3 - <a href='http://www.facebook.com/dragonbound.net' target='_blank'>DragonBound Community/News</a>"
    - "New Avatars: Phoenix & Frozen Warrior Set & Gold Backgrounds & Gold\n Foregrounds | Name Change Fixed | New Cash Charge 'GM' Payment Methods."